// Generated by Haxe 4.1.3

#pragma warning disable 109, 114, 219, 429, 168, 162
public class Test : global::haxe.lang.HxObject {
	
	public static void Main(){
		global::cs.Boot.init();
		global::Test.main();
	}
	public Test(global::haxe.lang.EmptyObject empty) {
	}
	
	
	public Test() {
		global::Test.__hx_ctor__Test(this);
	}
	
	
	protected static void __hx_ctor__Test(global::Test __hx_this) {
	}
	
	
	public static void main() {
		unchecked {
			global::haxe.Log.trace.__hx_invoke2_o(default(double), "#START", default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"main", "Test", "src/Test.hx"}, new int[]{1981972957}, new double[]{((double) (5) )}));
			global::TestControl sm = new global::TestControl();
			sm.Run();
			global::haxe.Log.trace.__hx_invoke2_o(default(double), "#END", default(double), new global::haxe.lang.DynamicObject(new int[]{302979532, 1547539107, 1648581351}, new object[]{"main", "Test", "src/Test.hx"}, new int[]{1981972957}, new double[]{((double) (8) )}));
		}
	}
	
	
}


